EDA
```{r}
library(tidyverse)
```
Understand how data is stored
Data validation
Determine rate of missing values
Clean data up 
Investigate distributions
Apply transformations
```{r}
diabetes <- read.csv("diabetes_binary_health_indicators_BRFSS2015.csv")
```

```{r}
diabetes$Diabetes_binary <- factor(diabetes$Diabetes_binary, levels = c(0, 1, 2), labels = c("No diabetes", "prediabetes", "diabetes"))
diabetes$HighBP <- factor(diabetes$HighBP, levels = c(0, 1), labels = c("No high BP", "High BP"))
diabetes$HighChol <- factor(diabetes$HighChol, levels = c(0, 1), labels = c("No high cholesterol", "High cholesterol"))
diabetes$CholCheck <- factor(diabetes$CholCheck, levels = c(0, 1), labels = c("No chol check in 5 years", "Yes chol check in 5 years"))
diabetes$Smoker <- factor(diabetes$Smoker, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$Stroke <- factor(diabetes$Stroke, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$HeartDiseaseorAttack <- factor(diabetes$HeartDiseaseorAttack, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$PhysActivity <- factor(diabetes$PhysActivity, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$Fruits <- factor(diabetes$Fruits, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$Veggies <- factor(diabetes$Veggies, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$HvyAlcoholConsump <- factor(diabetes$HvyAlcoholConsump, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$AnyHealthcare <- factor(diabetes$AnyHealthcare, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$NoDocbcCost <- factor(diabetes$NoDocbcCost, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$GenHlth <- factor(diabetes$GenHlth, levels = c(1,2,3,4,5), labels = c("Excellent", "Very good", "Good", "Fair", "Poor"))
diabetes$DiffWalk <- factor(diabetes$DiffWalk, levels = c(0, 1), labels = c("No", "Yes"))
diabetes$Sex <- factor(diabetes$Sex, levels = c(0, 1), labels = c("Female", "Male"))
diabetes$Age <- factor(diabetes$Age, levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13), labels = c("Age 18 to 24","Age 25 to 29","Age 30 to 34","Age 35 to 39","Age 40 to 44","Age 45 to 49","Age 50 to 54","Age 55 to 59","Age 60 to 64","Age 65 to 69","Age 70 to 74","Age 75 to 79","Age 80 or older"))
diabetes$Education <- factor(diabetes$Education, levels = c(1,2,3,4,5,6,9), labels = c("Never attended school or only kindergarten","Grades 1 through 8 (Elementary)", "Grades 9 through 11 (Some high school)", "Grade 12 or GED (High school graduate)", "College 1 year to 3 years (Some college or technical school)", "College 4 years or more (College graduate)", "Refused"))
diabetes$Income <- factor(diabetes$Income, levels = c(1,2,3,4,5,6,7,8,77,99), labels = c("Less than $10,000", "Less than $15,000 ($10,000 to less than $15,000)", "Less than $20,000 ($15,000 to less than $20,000)", "Less than $25,000 ($20,000 to less than $25,000)", "Less than $35,000 ($25,000 to less than $35,000)", "Less than $50,000 ($35,000 to less than $50,000)", "Less than $75,000 ($50,000 to less than $75,000)", "$75,000 or more", "Don’t know/Not sure", "Refused"))
diabetes$BMI <- format(diabetes$BMI, nsmall = 1)
diabetes$MentHlth <- format(diabetes$MentHlth, nsmall = 1)
diabetes$PhysHlth <- format(diabetes$PhysHlth, nsmall = 1)
```


```{r}
typeof(diabetes$BMI)
typeof(diabetes$MentHlth)
```

```{r}
colSums(is.na(diabetes))
```

```{r}
str(diabetes)
```

```{r}
attributes(diabetes)
```

```{r}
summary(diabetes)
```
















[Click here for the Modeling Page](Modeling.html)